### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by MartyF81** [petelapczynski/pantryraid#1]
The word cupboard is lowercase in index.php, all other options in the array are capitalized. 

This repo is locked down like Fort Knox so I couldn't commit the change for you. Weak.

**Comment by petelapczynski** [comment]
Thanks for the issue. MVP had static values and the capitalization was missed during UAT. Adding to Sprint 1 for dynamic option list based on previous entries.

**Comment by MartyF81** [comment]
I will have to keep a close eye on this.  The user "Lisa" has complained about proper grammar usage.
